sudo: required
services:
    - docker

script:
    - docker build -t sabbir/node .
    - docker images sabbir/node

before_deploy:
    - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD docker.io

deploy:
    provider: script
    script: docker push sabbir/node
    on:
        branch: master